WINDOW_HEIGHT = 600
WINDOW_WIDTH = 800
WINDOW_SIZE = (WINDOW_WIDTH, WINDOW_HEIGHT)
FPS_CAP = 60
TITLE = "PyInvaders"
PLAYER_SPEED = 150
PLAYER_FIRE_RATE = 10 # units?
MISSILE_SPEED = 200
PLAYER_MUZZLE_OFFSET_PX = (24, 0)

PLAYER = "player.png"
PLAYER_MISSILE = "player_missile.png"
ENEMY_SMALL = "small.png"
ENEMY_MEDIUM = "medium.png"
ENEMY_LARGE = "large.png"
ENEMY_SPECIAL = "special.png"
ENEMY_MISSILE = "enemy_missile.png"
WALL = "wall.png"
EXPLOSION = "explosion.png"
